apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJRVzV1YVdWaWRXNXVlVWRJT21kcGRHaDFZbDl3WVhSZk1URkJUMDlGVmtSSk1IbFZibE5VTVdsMVRtUlFVMTlZUjA5ck1FSlFaRFZvWVRWR1owb3pRbTEyVFVwalV6SjFNVTFaUzFaSGJteGFObEpuUm1OblpEbERUVnBMVWxsUVV6ZDRZbWh2Y2xWaWNnPT0ifX19
type: kubernetes.io/dockerconfigjson
